### ISSUE TITLE
Fix PR feedback items

### ISSUE THREAD

**Issue by KnockOutEZ** [brightshift/brightshift-ui#13]

**Comment by Chipsii** [comment]
The issues on the PR are resolved except for the icon package issue, and I plan to fix the icon package issue when I start working on the dashboard because the icon package is already in the dashboard branch so I don't need to add the package in the PR branch.

**Comment by KnockOutEZ** [comment]
> The issues on the PR are resolved except for the icon package issue, and I plan to fix the icon package issue when I start working on the dashboard because the icon package is already in the dashboard branch so I don't need to add the package in the PR branch.

Awesome! We can get back to this again later. Approving this PR
